- COMPILE
- doc/source/reference/index.rst
- doc/source/stdlib/index.rst
Looks like I had to install two packages to be able to compile the doc by myself. I added some indications about such requirements so the programmer/user won't be surprised by the lack of dependencies at compile time. 
Edit : Also fixing some mistypings or mistakes in the documentation.
> Added some infos on how to build the documentation.

- doc/source/stdlib/stdstringlib.rst
- sqstdlib/sqstdrex.cpp
Currently, a regexp like "\" will result in a nondeterministic malfunction as it attempts to continue parsing beyond the null terminator. This patch fixes that.
> fix parsing of incomplete regexp escape sequence

- doc/source/reference/api/object_manipulation.rst
- doc/source/reference/language/metamethods.rst
- squirrel/sqvm.cpp
- squirrel/sqvm.h
Just a small thing.
sqvm.cpp already had `#define TOP() (_stack._vals[_top-1])`
Shouldnt it have 
```
#define TARGET _stack._vals[_stackbase+arg0]
#define STK(a) _stack._vals[_stackbase+(a)]
```
also, instead of sqvm.h? Nothing else uses those and the names were colliding with something else I had.
> Tidy sqvm.h and docs fixes

- doc/source/reference/api/object_creation_and_handling.rst
- doc/source/reference/embedding/the_stack.rst
- include/squirrel.h
- squirrel/sqapi.cpp
this is an easy way to retrieve strings from the stack along with their size, to avoid useless strlens later. it's named PString to suggest that it's like a pascal-style PSTring, prefixed with the length--that's basically what it is.
It may be of dubious value so I put it in a branch for others to evaluate, but at least it's the kind of thing @mingodad is into also.  I think everyone here could think of about 90 functions to add to the core API and I don't know where it should end, but this one is very small. It just seems a shame to not be able to take advantage of the string length that squirrel already has.
> feature: add SQPString and sq_getpstring()

- doc/source/reference/language/builtin_functions.rst
- doc/source/stdlib/stdstringlib.rst
- sqstdlib/sqstdstring.cpp
this is so we can avoid having to write print(format( all the time. it should be a little more lean than writing that function in lua yourself (can work entirely from scratchpad this way).  It's been put in the string stdlib because it's similar to format().
It's a very clean solution, but I don't know what you think of the philosophy of it.
> feature: add a printf function to the string stdlib

- include/squirrel.h
- sq/sq.c
- squirrel/sqclass.cpp
- squirrel/sqstate.cpp
With this small change non-gnu compilers will not warn on unused function arguments.
> FIX: no warnings on unused arguments on non-gnu compilers

- squirrel/sqapi.cpp
Support sq_getinteger() for bools.
Returns SQFalse or SQTrue in the SQInteger. 
Useful for format("%d",mybool)
Rationale: squirrel seems to apply some logic to type conversion which makes sense to any C-oriented programmer. I think this one falls under that category, and its absence is just an oversight.
Another way to do this might be to classify bool as numeric (and it would be automatically handled by the case above), but that could have wide-ranging consequences. But if that sounds interesting, we can discuss it here. Otherwise just this makes debugging bools much more pleasant.
> support sq_getinteger() for bools 

- include/squirrel.h
- squirrel/sqapi.cpp
by #defining _SQ_CONFIG_INCLUDE, that file will be #included early om squirrel.h
This will let you more easily configure how squirrel gets built.
(also fix a typo in an error message)
> add mechanism for configuring squirrel by optionally #including a file in squirrel.h

- README
- doc/make.bat
- doc/source/reference/language/functions.rst
- doc/source/stdlib/stdstringlib.rst
- sqstdlib/sqstdio.cpp
- sqstdlib/sqstdrex.cpp
- sqstdlib/sqstdstring.cpp
- squirrel/sqlexer.cpp
Convert source files to Unix EOL mode, convert .bat files to DOS EOL
mode, de-tabify and strip trailing whitespace.
> Normalize whitespace.

- sqstdlib/sqstdstring.cpp
The invoker should at least know that the value he specified is not of the correct type.
> Never assume the format is actually a string.

- CMakeLists.txt
CMAKE_SOURCE_DIR points at the root project's source dir,
which is wrong when building squirrel as a git submodule.
CMAKE_CURRENT_SOURCE_DIR points at the dir of the current
CMakeLists.txt and thus should be used most of the time.
> Fix building as a git submodule.

- sqstdlib/Makefile
- squirrel/Makefile
Updated the Makefiles in squirrel and sqstdlib folder to have same set of variables in order to be more coherent as well as be able to pass their values from command line.
The variables OUT and INCZ can be set from command line, while DEFS can be set via CC_EXTRA_FLAGS -- I was not sure if the purpose of the existing `DEFS= ` was to reset an eventual existing value, given that DEFS is quite common out there in build systems. If the purpose was not to reset DEFS, then it can be set to `DEFS?=` and CC_EXTRA_FLAGS won't be needed.
The target is to make it easier to embed the interpreter directly into another project source code tree by just copying the two folders. The build system of the host project then can set these variables when invoking make for squirrel, to set custom compile flags …
> configurable makefile vars from command line

- squirrel/sqapi.cpp
- squirrel/sqbaselib.cpp
- squirrel/sqclass.cpp
- squirrel/sqcompiler.cpp
- squirrel/sqdebug.cpp
- squirrel/sqfuncstate.cpp
- squirrel/sqobject.cpp
- squirrel/sqobject.h
- squirrel/sqstate.cpp
- squirrel/sqtable.cpp
- squirrel/sqtable.h
- squirrel/sqvm.cpp
PR #100 changed `type` to `sqtype`.
Someone pointed out `sq_type` did the same thing.
It's in the public API already.
So this PR uses that instead. It's not very important but it's a worthwhile tidying.
PR #103 kind of attempts to do the same thing but oppositely and wrongly; it needs to be closed.
> replace newly added sqtype with previously existing sq_type

- squirrel/sqapi.cpp
This PR fixes a bug where sq_newmember and sq_rawnewmember did not pop their arguments from the stack. This makes it comply with the documentation (http://www.squirrel-lang.org/squirreldoc/reference/api/object_manipulation.html?highlight=newmember#c.sq_newmember).
Changing this function might break existing code and I also haven't tested it much (yet). Please advise.
An alternate route is to update the wording in the documentation if we don't want to arguments to be popped.
> sq_newmember and sq_rawnewmember argument popping

- doc/source/reference/embedding/references_from_c.rst
In order to make the examples compile in master on windows I had to change this.
> Fix errors in documentation source code

- doc/source/reference/api/object_manipulation.rst
- doc/source/reference/embedding/calling_a_function.rst
- doc/source/reference/embedding/compiling_a_script.rst
- doc/source/reference/embedding/creating_a_c_function.rst
- doc/source/reference/embedding/references_from_c.rst
Here are the bugs I found in the embedding-part of the documentation in doing my documentation tests (see PR #115 ). I also snuck in some more information in sq_get, let me know I am mistaken.
Not fixed:
In compiling_a_c_function.rst the line "printf("arg %d is ",n);" is not 64-bit compatible but I don't have a good clean fix for that.
> Fix some small bugs in the documentation examples

- squirrel/sqbaselib.cpp
Instead of trying to allocate invalid size and most probably crashing with out-of-memory
> Raise error for negative size in array_resize()

- doc/source/reference/language/builtin_functions.rst
- squirrel/sqbaselib.cpp
Support filter() for tables just like existing filter() for arrays.
Filter callback is the same as for array.filter(), ie function(key, value)
> Implement table.filter() default delegate in base library

- doc/source/reference/language/builtin_functions.rst
- squirrel/sqbaselib.cpp
for easy chaining
something like
local ar = [0,1,3,4]
ar.append(5).extend([6,7,8]) and etc
> now container modification methods return object itself in all cases

- CMakeLists.txt
Toralf noticed a minor infelicity in option declarations:
```
build $ cmake -DLONG_OUTPUT_NAMES=YES ..
CMake Warning:
Manually-specified variables were not used by the project:
LONG_OUTPUT_NAMES
```
Note, CMake complains here about "unused" LONG_OUTPUT_NAMES.
The option is used but not declares as user-tweakable via 'option()'.
This change adds declarations for variables used in Gentoo.
Reported-by: Toralf Förster
Bug: https://bugs.gentoo.org/659880
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
> CMakeLists.txt: explicitly declare LONG_OUTPUT_NAMES and DISABLE_STATIC

- doc/source/reference/api/object_creation_and_handling.rst
- include/squirrel.h
- squirrel/sqapi.cpp
For native closures this method returns _nparamscheck value
which can be negative when function accepts variable number of
arguments - and it's incorrect to cast it to unsigned.
Also, _nparameters, _noutervalues and _nparamscheck fields are
actually signed integers, so it is better to keep them signed.
And casting _noutervalues is ok since it has enough capacity.
> Make params count type signed in sq_getclosureinfo()

- squirrel/sqobject.cpp
Functions SafeRead and CheckTag have parameter "SQWRITEFUNC read". Now this is corrected to "SQREADFUNC read".
> Make 'read' parameter of SafeRead and CheckTag of type SQREADFUNC

- doc/source/reference/language/builtin_functions.rst
- squirrel/sqbaselib.cpp
Sometimes it is needed to process array when result depends not on item value only, but also from its position or collection content.
So make array.map() and array.apply() functions more flexible by supporting optional additional parameters in callback: item index and reference to array being processed.
(The design is like in https://underscorejs.org/#map)
> Allow additional parameters in array.map()/array.apply() handler

- squirrel/sqcompiler.cpp
This error isn't as clear as it could be, but I think this would be break, not brake.
> Spelling fix in sqcompiler error

- squirrel/sqbaselib.cpp
> albertodemichelis/squirrel/squirrel/sqbaselib.cpp: In function ‘SQInteger __map_array(SQArray*, SQArray*, HSQUIRRELVM)’:
> albertodemichelis/squirrel/squirrel/sqbaselib.cpp:646:9: warning: ‘nArgs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>         if (nArgs >= 4)
>         ^
fixes #205
> fix compilation warning

- squirrel/sqvm.cpp
This actually makes me worried if doubles are still supported properly in latest version, but this fixes the build at least.
> Fix build when SQUSEDOUBLE is defined

- sqstdlib/sqstdstring.cpp
In current implementation string "dest" is used as "format string" in call to "printfunc".
This leads to unpredictable behavior if something like format string is produced by "sqstd_format".
For example string "%%*s" once formated results in "%*s", passed to "printfunc" will try to read two integer arguments (which are not given).
Quick test:
sq>printf("%%*s")
%*s
> Set format string for _string_printf

- squirrel/sqvm.cpp
Report error if called object is not OT_CLOSURE, OT_NATIVECLOSURE nor OT_CLASS
> Set error message if called object is not callable

- doc/source/stdlib/stdstringlib.rst
- sqstdlib/sqstdstring.cpp
Current behavior threads all separators as important, as it is the case in CSV files.
But for case where separators are just sequence of spaces 'split' returns unpredictable number of empty elements.
In proposed implementation there is a optional argument (preserving original behavior) that will skip adding any empty element to resulting array.
Example of such input is:
local a = split("  123   456", " ")
--> [ "", "", "123", "", "", "","456"]   (default)
local a = split("  123   456", " ",true)
--> [ "123","456"]  (without empty elements)
> Add optional argument 'skipempty' to split function

- squirrel/sqtable.h
Using the SQObject& is enough for HashObj() function.
In the following code
```
RefTable::RefNode *RefTable::Get(SQObject &obj,SQHash &mainpos,RefNode **prev,bool add)
{
RefNode *ref;
mainpos = ::HashObj(obj)&(_numofslots-1);
```
obj was an SQObject and because HashObj() accepted SQObjectPtr&, a temporary SQObjectPtr was created and refcounting was performed, which only lead to unnecessary overhead.
> Fix creating unnecessary temporary object with refcount

- sq/CMakeLists.txt
Attempting to build Squirrel with CMake and `-DDISABLE_DYNAMIC=ON` will fail.
The reason seems to be a mistake: in `sq/CMakeLists.txt`, at line 18, the alias generated for `squirrel::interpreter_static` is actually an alias for the dynamically-linked `sq` instead of `sq_static`.
Since the code for static builds is the same as the code for dynamic builds but with "_static" appended to all names, I assumed it was a simple omission and changed `sq` to `sq_static`, which fixed the problem.
> Fix interpreter CMake alias for static builds

- CMakeLists.txt
Fixes #243 
There is a line in CMakeLists.txt which prevents builds with `SQ_DISABLE_INSTALLER` from working properly. It seems to be a line that should be guarded by `if(NOT SQ_DISABLE_INSTALLER AND NOT SQ_DISABLE_CMAKE_INSTALLER)`, so I moved it inside the block.
> Move CMake installer line in if() statement

- squirrel/sqvm.cpp
sq_resume crashes (ci is null) when called on a dead generator.
> fixed sq_resume

- sqstdlib/sqstdsystem.cpp
IOS macro is not automatically defined when compiling to iOS devices.
The reliable way to detect iOS is to detect `__APPLE__`, include <TargetConditionals.h> and then check for TARGET_OS_IPHONE.
See https://stackoverflow.com/questions/5919996/how-to-detect-reliably-mac-os-x-ios-linux-windows-in-c-preprocessor and https://gist.github.com/TatsuyaOGth/7a6006c9ddecbc3fb655
> Fix iOS detection

- squirrel/sqstate.cpp
Do not let the compiler optimize out security check. See #294
> Fix undefined behavior

- squirrel/squtils.h
Fix warning build on gcc with `memmove()` function between `void*` and `struct SQObjectPtr` types :
```
$ make
mkdir -p lib
mkdir -p bin
cd squirrel; make
make[1]: Entering directory '/home/user/Documents/squirrel/squirrel'
cc -O2 -fno-exceptions -fno-rtti -Wall -fno-strict-aliasing -c sqapi.cpp sqbaselib.cpp sqfuncstate.cpp sqdebug.cpp sqlexer.cpp sqobject.cpp sqcompiler.cpp sqstate.cpp sqtable.cpp sqmem.cpp sqvm.cpp sqclass.cpp -I../include -I. -Iinclude 
In file included from sqobject.h:5,
from sqpcheader.h:17,
from sqapi.cpp:4:
squtils.h: In instantiation of 'void sqvector<T>::remove(SQUnsignedInteger) [with T = SQObjectPtr; SQUnsignedInteger = long long unsigned int]':
sqarray.h:83:23:   required from here
squtils.h:98:20: warning: 'void* memmove(void*, const void*, size_t)' writing …
```
> Fix warning build with memmove
